FROM golang:1.22 as builder

WORKDIR /app

# Copia solo lo necesario
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o server ./grpc-server/server.go

# necesario para que funcione alpine
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o server ./grpc-server/server.go 

FROM alpine:3.17
WORKDIR /app
COPY --from=builder /app/server .
EXPOSE 8081
CMD ["./server"]
