FROM golang:1.22 as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o suscriber ./suscriber.go

FROM alpine:3.17

WORKDIR /app

COPY --from=builder /app/suscriber /app/

RUN chmod +x /app/suscriber

EXPOSE 8080

CMD ["./suscriber"]
