FROM golang:1.22 AS builder
WORKDIR /app
COPY . .
RUN GOARCH=amd64 CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o KafkaSuscriber ./kafka/main.go

FROM alpine:3.17 AS final

WORKDIR /app

COPY --from=builder /app/KafkaSuscriber /app/

RUN chmod +x /app/KafkaSuscriber
EXPOSE 8085
CMD ["./KafkaSuscriber"]
