apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-writer
  template:
    metadata:
      labels:
        app: rabbit-writer
    spec:
      containers:
      - name: rabbit-writer
        image: andrekss/writer-image
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-writer
spec:
  selector:
    app: rabbit-writer
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
