FROM golang:1.22 as builder

WORKDIR /app

# Copia solo lo necesario
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o rabbit-writer ./grpc-server/rabbit/main.go

# necesario para que funcione alpine
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o rabbit-writer ./grpc-server/rabbit/main.go

FROM alpine:3.17
WORKDIR /app
COPY --from=builder /app/rabbit-writer .
EXPOSE 8084
CMD ["./rabbit-writer"]
