apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: Proyecto2
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weather-tweets-system
                port:
                  number: 80
