apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-consumer
  template:
    metadata:
      labels:
        app: rabbit-consumer
    spec:
      containers:
      - name: rabbit-consumer
        image: andrekss/consumer-image
        ports:
        - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-consumer
spec:
  selector:
    app: rabbit-consumer
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
