FROM golang:1.22 as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o RabbitSuscriber ./RabbitSuscriber.go

FROM alpine:3.17

WORKDIR /app

COPY --from=builder /app/RabbitSuscriber /app/

RUN chmod +x /app/RabbitSuscriber

EXPOSE 8083

CMD ["./RabbitSuscriber"]
