FROM golang:1.22 AS builder
WORKDIR /app
COPY . .
RUN GOARCH=amd64 CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o RabbitConsumer ./rabbit/main.go

FROM alpine:3.17 AS final

WORKDIR /app
COPY --from=builder /app/RabbitConsumer /app/
RUN chmod +x /app/RabbitConsumer
EXPOSE 8086
CMD ["./RabbitConsumer"]
