FROM python:3.10-alpine

# Instala cronie (cron) en Alpine
RUN apk add --no-cache cronie

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY app.py .
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
