version: '3.8'

services:
  api-go:
    build:
      context: ./Deployments
    container_name: api-go
    ports:
      - "8081:8081"


  api-rust:
    build:
      context: ./Rust-Api
    container_name: api-rust
    ports:
      - "8082:8082"
    depends_on:
      - api-go  

  grpc-server:
    build:
      context: ./Deployments
      dockerfile: grpc-server/dockerfile
    container_name: grpc-server
    ports:
      - "8083:8081"

  # brokers
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # Zookeeper util para kafka
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENERS:            PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT:        zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER:       "yes"
      KAFKA_ENABLE_KRAFT:             "no"