version: '3.8'

services:
  api-go:
    build:
      context: ./Deployments
    container_name: api-go
    ports:
      - "8081:8081"


  api-rust:
    build:
      context: ./Rust-Api
    container_name: api-rust
    ports:
      - "8082:8082"
    depends_on:
      - api-go  
