apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-writer
  template:
    metadata:
      labels:
        app: kafka-writer
    spec:
      containers:
      - name: kafka-writer
        image: andrekss/writer-image
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-writer
spec:
  selector:
    app: kafka-writer
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
