apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-proyecto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proyecto2
  template:
    metadata:
      labels:
        app: proyecto2
    spec:
      containers:
      - name: goweb
        image: andrekss/goweb:v3
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
