# Etapa de build
FROM rust:latest as builder

WORKDIR /app
COPY . .
RUN cargo build --release

FROM rust:latest

COPY --from=builder /app/target/release/Rust-Api /usr/local/bin/Rust-Api

CMD ["Rust-Api"]
