FROM rust:1.74 as builder

WORKDIR /usr/src/app

COPY . .

RUN cargo build --release

FROM ubuntu:24.04

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

# Crear directorio de ejecución
WORKDIR /usr/local/bin

COPY --from=builder /usr/src/app/target/release/rust-api rust-api

EXPOSE 8080

# Comando para ejecutar
CMD ["./rust-api"]
