# Etapa de build
FROM rust:latest as builder

WORKDIR /app
COPY . .
RUN cargo build --release

# Etapa final
FROM ubuntu:24.04
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/Rust-Api /usr/local/bin/Rust-Api
CMD ["Rust-Api"]
